### ISSUE TITLE
Update #7, New User Story: I want to be able to read a movie review based on my search

### ISSUE THREAD

**Issue by yvonne-liu** [FAC10/week3-facxmachine-api#19]
Relates to issue #7: 

The YouTube API pulls in too much code from their code base, so we've decided to switch gears _again_ and this time: 

We're continuing along the theme of 'What movie shall I watch?', but instead of pulling the videos from YouTube API, we're going to pull movie reviews from NYT API. 

User stories:

- [x] "I want to be able to search for a specific movie genre (optionally filtering by actor) and get a list of films ranked by popularity "
- [x] "I want to be able to read a snippet of the movie review"

**Comment by yvonne-liu** [comment]
@oliverjam @bo-bok @Akin909 does this updated user story look okay to you guys?

**Comment by oliverjam** [comment]
Yes, except we're not filtering by actor anymore :)

**Comment by jessicasalmon** [comment]
done 🎉
