### ISSUE TITLE
Ordering functions in index.js

### ISSUE THREAD

**Issue by emilyb7** [FAC10/week3-facxmachine-api#43]
Your code would be more readable if `attachListener`were at the end, rather than randomly between all the other function declarations :)

**Comment by jessicasalmon** [comment]
great point, thanks! I think because we wrote it early on we never thought about how it would read if it were left there. Sorted :)

**Comment by jessicasalmon** [comment]
actually - scrap that it broke everything :woman_facepalming: moved it to somewhere slightly more logical and will come back to it later

**Comment by oliverjam** [comment]
Done 👍
