### ISSUE TITLE
Slightly confusing callback linking

### ISSUE THREAD

**Issue by finnhodgkin** [FAC10/week3-facxmachine-api#47]
'getMoviesByGenre' directly calls the next function 'getTrailers'

This could be cleaned up and would allow for more scalability if you used a waterfall or similar to call the functions in order. That way you could, for example, add in data handling between API calls without needing to swap out the function names within multiple functions.

**Comment by oliverjam** [comment]
We would definitely have benefitted from a waterfall. I think it's much less confusing now that the function order in the code follows the same order as the data does through the API calls. Probably as close to fixing this issue as we're gonna get
