### ISSUE TITLE
TV Movie and Documentary don't work 

### ISSUE THREAD

**Issue by yvonne-liu** [FAC10/week3-facxmachine-api#61]
See error message:

```
Uncaught TypeError: Cannot read property 'key' of undefined
    at index.js:47
    at XMLHttpRequest.request.onreadystatechange (index.js:76)
```

**Comment by jessicasalmon** [comment]
I think that these might be the categories that we 'found' along the way, after we had added the initial list from the docs. Any thoughts on that @oliverjam?
