### ISSUE TITLE
New User Story: I can search for movies by genre and then click to view trailers

### ISSUE THREAD

**Issue by oliverjam** [FAC10/week3-facxmachine-api#7]
Okay so the API won't actually let us see if two actors were in the same film (relates #1)

We're going to pivot to creating a 'What movie shall I watch?' app.

User stories:
- [x] "I want to be able to search for a specific movie genre (optionally filtering by actor) and get a list of films ranked by popularity "
- [x] "I want to be able to click a 'Trailer' button to view the trailer for a given movie"

**Comment by jessicasalmon** [comment]
we dids it 🎉
